name: simple_audio_recorder
description: "Simple layout for audio recording"
version: 0.2.1
homepage: https://github.com/rafaelmaia8384/simple_audio_recorder

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  record: ^5.2.0 
  sound_waveform: ^1.0.1
  wakelock_plus: ^1.2.8
  uuid: ^4.5.1
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
